/**
 * lib/me/data.ts — Raw resume data (unvalidated).
 * Do not import this directly — import `ME` from `lib/me` for the validated singleton.
 */

export const rawMeData = {
  profile: {
    firstName: "Pakorn",
    firstNameTH: "ปกร",
    lastName: "Chaowanaprasert",
    lastNameTH: "เชาวนประเสริฐ",
    nickname: "Kur",
    nicknameTH: "เกื้อ",
    title: "Lead Developer",
    tagline: "ตั้งใจสร้างระบบที่ scale ได้จริง และเขียน code ที่เพื่อนร่วมทีมอ่านต่อได้สบาย",
    location: "Bangna Bangkok, Thailand",
    gender: "male" as const,
    dateOfBirth: "1994-02-27",
    militaryStatus: "ได้รับการยกเว้น (เรียน รด.)",
  },

  contact: {
    email: "patapuputapa@gmail.com",
    phone: "0885797989",
    // linkedin / website intentionally omitted until available
  },

  summary: {
    bio: "สวัสดีครับ ผมเป็น Lead Developer ประสบการณ์ 8 ปี งานที่ทำมีทั้งออกแบบ architecture วาง database schema ดูแล production และนำทีมทำ CRM platform ให้ลูกค้าองค์กรมากกว่า 15 ราย เช่น Millennium Auto และ CP-Meiji ส่วนที่ผมชอบที่สุดคือการทำระบบ config-driven ที่ทีมเอาไปต่อยอดเองได้โดยไม่ต้องรอ dev ช่วงหลังผมทำงานแบบ AI-first ใช้ Claude Code เป็นเครื่องมือหลักครับ",
    yearsOfExperience: 8,
    highlights: [
      "ทำ CRM platform ให้ลูกค้าองค์กร 15+ ราย แต่ละรายตั้ง config ของตัวเองบน codebase เดียว",
      "ทำระบบ config-driven ที่ลดเวลาสร้างหน้าใหม่จาก 2-3 วัน เหลือ 2-3 ชั่วโมง",
      "ดูแลงานเองทั้ง architecture, dev, deploy และ migration",
      "นำทีม dev 5 คน วาง code review culture ให้คุณภาพงานนิ่ง",
      "วาง CI/CD ด้วย Docker, Nginx, Jenkins, Kubernetes รันบน Azure และ IBM Cloud",
      "ทำ CRM กว่า 90 หน้า ครอบคลุมงานหลายส่วน เช่น Lead, Opportunity ไปจนถึง Customer 360",
      "ทำ real-time feature ด้วย Socket.IO เช่น chat, AI chatbot, live notification",
    ],
  },

  skills: {
    // Everything here also appears in the categorised lists below, at level 80
    // or above. This is the "if you only read one line" stack.
    core: [
      "TypeScript",
      "JavaScript",
      "React",
      "Next.js",
      "Node.js",
      "PostgreSQL",
      "Prisma",
      "Redis",
      "Docker",
      "Claude Code",
    ],
    languages: [
      { name: "JavaScript", level: 90 },
      { name: "TypeScript", level: 80 },
      { name: "PHP", level: 60 },
    ],
    frameworks: [
      { name: "React", level: 90 },
      { name: "Next.js", level: 85 },
      { name: "Node.js", level: 80 },
      { name: "Ant Design", level: 90 },
      { name: "Material-UI", level: 75 },
      { name: "Vue.js", level: 65 },
      { name: "Prisma", level: 80 },
      { name: "Socket.IO", level: 75 },
    ],
    databases: [
      { name: "PostgreSQL", level: 85 },
      { name: "MySQL", level: 70 },
      { name: "Redis", level: 85 },
    ],
    devops: [
      { name: "Docker", level: 80 },
      { name: "Nginx", level: 75 },
      { name: "Jenkins", level: 70 },
      { name: "Kubernetes", level: 65 },
    ],
    tools: [
      { name: "Git", level: 90 },
      { name: "n8n", level: 75 },
      { name: "Figma", level: 60 },
      { name: "GitHub Copilot", level: 70 },
      { name: "Kiro (AI IDE)", level: 75 },
      { name: "Claude Code", level: 85 },
    ],
    softSkills: [
      "Config-driven System Design",
      "Team Leadership & Code Review Culture",
      "Database Schema Design & Migration Planning",
      "แปลง business requirement เป็น technical solution",
      "Cross-project Code Sharing & Reusable Architecture",
      "CRM Domain Expertise (Sales, Marketing, Service, Field Service)",
      "Multi-tenant SaaS Architecture Design",
      "Real-time System Design (WebSocket, Event-driven)",
      "AI-Assisted Development ด้วย Claude Code",
    ],
  },

  experience: [
    {
      company: "MSC",
      workModel: "remote" as const,
      startDate: "2019-09",
      endDate: "present",
      roles: [
        { title: "Development Leader", startDate: "2025-01", endDate: "present" },
        { title: "Senior Programmer", startDate: "2021-01", endDate: "2024-12" },
        { title: "Programmer", startDate: "2019-09", endDate: "2020-12" },
      ],
      teamSize: 5,
      summary: "เข้ามาเป็น Programmer ปี 2019 ขึ้นเป็น Senior ในปี 2021 และเป็น Development Leader ตั้งแต่ปี 2025 ดูแลทีม dev 5 คน พัฒนา CRM platform ให้ลูกค้าองค์กร 15+ ราย",
      responsibilities: [
        "ออกแบบ architecture และ database schema ให้ทั้ง S-CRM (React SPA) และ Next-S-CRM (Next.js 15)",
        "ดูแล production ทั้ง dev, UAT และ production environment บน Azure และ IBM Cloud",
        "สร้าง shared component ใช้ข้าม project กว่า 80 ชิ้น",
        "วาง migration plan ย้ายระบบเก่าเข้า platform ใหม่ ทั้ง schema, data mapping และ UX flow",
        "ออกแบบ CRM module หลายตัว เช่น Lead, Opportunity, Case และ Field Service",
        "พัฒนา real-time feature ด้วย Socket.IO ทั้ง chat, notification และ live update",
        "สร้าง workflow automation engine ให้ case management",
        "ออกแบบ role-based access control และ visible function system รองรับ multi-tenant",
        "Integrate Azure AD SSO (MSAL) ให้ลูกค้า enterprise",
      ],
      achievements: [
        { metric: "ทำ Custom CRM platform", value: "15+ ลูกค้าองค์กร", context: "Well, WDC, Panel Plus, Modernform, Central Food, Millennium Auto และอื่นๆ" },
        { metric: "พัฒนา S-ERP", value: "All module dashboards", context: "ระบบ ERP ครบทุก module" },
        { metric: "สร้าง CP-Meiji Web App", value: "Solo architect, 30+ tables, 4 doc types", context: "ออกแบบและพัฒนาเองตั้งแต่ต้น โดยไม่มีระบบต้นแบบให้อ้างอิง" },
        { metric: "สร้าง Chat Assistance", value: "ระบบ chat ใน CRM", context: "Socket.IO chat ต่อกับ n8n chatbot และ AI Agent context เพิ่ม engagement ของ end-user" },
        { metric: "พัฒนา Next-S-CRM", value: "CRM generation ใหม่", context: "ปรับ architecture ใหม่ทั้งหมดด้วย Next.js 15" },
        { metric: "สร้าง S-Hospitality", value: "Dynamic & Master Components", context: "reusable components สำหรับสาย hospitality" },
        { metric: "CRM หลายโมดูล", value: "90+ routes/pages", context: "ครอบคลุม Lead, Opportunity, Quotation, Field Service และ Customer 360" },
        { metric: "Kubernetes deployment", value: "Azure + IBM Cloud", context: "Multi-environment CI/CD pipeline" },
        { metric: "Landing Page Builder", value: "Marketing self-service tool", context: "ให้ทีม marketing สร้าง landing page ได้เองโดยไม่ต้องรอ dev" },
      ],
      clients: [
        "Well", "WDC", "Peneak", "Panel Plus", "Modernform", "Enraf",
        "CSH", "Central Food", "Traphet", "TBC", "T-Life", "T-Mill",
        "CP-Meiji", "Millennium Auto",
      ],
      techStack: ["JavaScript", "React", "Next.js", "Ant Design", "Material-UI", "Styled Components", "Socket.IO", "Chart.js", "Nivo", "n8n", "PostgreSQL", "Prisma", "Redis", "Docker", "Nginx", "Jenkins", "Kubernetes", "Azure AD (MSAL)", "Google Maps API", "Git"],
    },
    {
      company: "CDG",
      workModel: "onsite" as const,
      startDate: "2017-11",
      endDate: "2019-04",
      roles: [
        { title: "Programmer", startDate: "2017-11", endDate: "2019-04" },
      ],
      summary: "พัฒนา web application สำหรับระบบสอบและระบบเครื่องราชอิสริยาภรณ์ของหน่วยงานรัฐ",
      responsibilities: [
        "พัฒนา frontend ด้วย Vue.js และ React",
        "เขียน backend API ด้วย PHP",
        "ออกแบบและ optimize SQL queries",
      ],
      achievements: [
        { metric: "ปรับ performance", value: "ลด query time", context: "optimize SQL queries สำหรับข้อมูลขนาดใหญ่" },
        { metric: "เรียนรู้ stack ใหม่", value: "4 ภาษา/frameworks", context: "JS, Vue, React, PHP ภายในปีแรก" },
      ],
      clients: [],
      techStack: ["PHP", "JavaScript", "Vue.js", "React", "MySQL", "Git"],
    },
  ],

  projects: [
    {
      name: "S-CRM Platform",
      category: "CRM Platform",
      description: "CRM platform หลักของบริษัท deploy ให้ลูกค้าองค์กร 15+ ราย แต่ละรายมี customization และ module ต่างกัน ดูแลและพัฒนาต่อเนื่องมากกว่า 4 ปี",
      role: "เริ่มจาก Developer แล้วขึ้นมาเป็น Lead Developer อยู่กับโปรเจกต์นี้มาตั้งแต่แรก ดูแล architecture, deployment, code review และ migration",
      techStack: ["React 16", "JavaScript", "Ant Design", "Material-UI", "Styled Components", "Socket.IO", "Chart.js", "Nivo", "React Router", "Redux", "Axios", "PostgreSQL", "Redis", "Docker", "Nginx", "Jenkins", "Kubernetes", "Azure AD (MSAL)", "GitHub Copilot"],
      highlights: [
        "รองรับลูกค้าองค์กร 15+ รายบน codebase เดียว เปิดลูกค้าใหม่ด้วยการตั้ง config แทนการ fork โค้ด อยู่บน production มา 4 ปีกว่าแล้ว",
        "ลูกค้าแต่ละรายมี config และ module เป็นของตัวเอง แต่ใช้ codebase เดียวกัน",
        "ดูแล production ด้วย Docker, Nginx, Jenkins และ Kubernetes บน Azure และ IBM Cloud",
        "สร้าง shared component ใช้ข้าม client project",
        "ย้ายระบบเก่าเข้า platform ใหม่ ออกแบบและลงมือทำเองทั้ง database schema และ UX",
        "Customer Journey tracking และ Churn Rate analysis",
        "Multi-format reporting ทั้ง Excel export, PDF viewer และ chart dashboard (Nivo, Chart.js)",
        "Role-based access control และ visible function system",
        "Azure AD SSO ให้ลูกค้า enterprise",
        "Landing Page Builder ให้ทีม marketing ใช้เอง",
      ],
    },
    {
      name: "Full-S-CRM (Next-S-CRM)",
      category: "CRM Platform",
      description: "CRM generation ใหม่ที่ redesign architecture ทั้งหมดจาก S-CRM เดิม ย้ายจาก React SPA มาเป็น Next.js 15 App Router เปลี่ยนจาก raw SQL เป็น Prisma ORM เพิ่ม Redis session/cache layer และ config-driven CRUD system ที่ลด boilerplate ได้กว่า 70%",
      role: "Lead Developer & Architect ออกแบบ architecture ใหม่ทั้งหมด สร้าง core framework และนำทีมพัฒนา",
      techStack: ["Next.js 15", "React 19", "JavaScript", "PostgreSQL", "Prisma", "Redis", "Docker", "Nginx", "Ant Design", "Tailwind CSS", "MinIO", "Azure AD", "n8n", "Kiro (AI IDE)", "Claude Code"],
      highlights: [
        "ลด boilerplate ลงกว่า 70% หน้า CRUD ใหม่เลยใช้เวลาจาก 2-3 วัน เหลือ 2-3 ชั่วโมง",
        "Centralized CRUD Helper รวม auto audit field, access control, transaction และ audit logging ไว้ที่เดียว",
        "Config-driven Form & Table ที่สร้างหน้า CRUD ใหม่ได้ภายในชั่วโมงจาก config ล้วน",
        "Interactive Prisma transaction ผ่าน Redis key จึงไม่ต้อง hold DB connection ค้างไว้",
        "ModelEvent System เป็น post-write hook ที่ trigger business logic ให้อัตโนมัติหลัง CRUD",
        "Row-level access control ที่ filter ข้อมูลตาม permission ให้เองผ่าน CRUD helper",
        "Validation engine แบบ expression (filtrex) กำหนด rule ผ่าน config ได้ และรองรับ CSP",
        "Codebase เดียวรองรับลูกค้าหลายรายผ่าน dynamic module system",
        "Azure AD SSO ต่อกับ Lucia v3 Auth พร้อม PKCE flow",
        "Centralized error handling ที่ log ลง DB และเปิด Azure Planner task ให้เองเมื่อเจอ critical issue",
        "พัฒนาด้วย AI-assisted workflow ทั้ง Kiro และ Claude Code",
      ],
    },
    {
      name: "CP-Meiji Material Request",
      category: "Enterprise Web App",
      description: "ระบบ Material Request ของ CP-Meiji ที่ผมออกแบบและพัฒนาเองตั้งแต่ต้น มีทั้ง multi-department approval workflow, dynamic form engine, การ migrate จากระบบเดิม และรองรับเอกสาร 4 ประเภท (Create, Extend, Edit, Deletion)",
      role: "Solo Architect & Full Stack Developer ดูแล architecture, DB schema, UX flow, expression engine, access control และ migration plan เองทั้งหมด โดยไม่มีระบบต้นแบบให้อ้างอิง",
      techStack: ["Next.js 15", "React 19", "JavaScript", "PostgreSQL", "Prisma", "Redis", "Ant Design", "Tailwind CSS", "MinIO", "Azure AD (MSAL)", "Lucia Auth", "Docker", "Nginx"],
      highlights: [
        "แทนที่ระบบเดิมได้ทั้งหมดโดยข้อมูลไม่หาย ย้ายการตั้งค่าฟอร์มมาไว้ในมือ admin ที่เพิ่มหรือแก้ field เองได้โดยไม่ต้องรอ dev และยิงข้อมูลเข้า SAP อัตโนมัติเมื่อ approval ครบ",
        "Database schema 30+ table ที่ normalize ให้รองรับ dynamic field, multi-level approval chain และ versioned material flow",
        "Config-driven form engine โครงสร้าง MaterialFlow → Section → Input ที่ admin กำหนด field, validation และ condition ได้เองโดยไม่ต้องแก้ code",
        "Expression engine (filtrex) สำหรับ rule แบบ requireIf, disableIf, defaultIf ที่ evaluate ได้ทั้งฝั่ง client และ server แบบ CSP-safe",
        "Route approval หลายชั้น รองรับทั้งอนุมัติแบบเรียงลำดับและแบบขนาน มี delegate manager และเปิด level ถัดไปให้อัตโนมัติ",
        "แยก permission ระดับ own/full/none ราย user ราย resource",
        "Azure AD SSO แบบ PKCE ต่อกับ Lucia session และเก็บ session ใน Redis",
        "เอกสาร 4 ประเภทที่มี flow และ validation ต่างกัน จัดการอยู่บน codebase เดียว",
        "สร้างไฟล์ TXT ส่ง SAP อัตโนมัติเมื่อ approval chain ครบ แล้ว convert เป็น Master Item",
        "Cache material flow config ไว้ 5 นาทีใน Redis เพื่อตัด DB query ซ้ำ",
        "ย้ายข้อมูลจากระบบเดิมเข้า schema ใหม่โดยไม่สูญเสียข้อมูล",
      ],
    },
    {
      name: "S-ERP Dashboard",
      category: "ERP System",
      description: "พัฒนา dashboard สำหรับระบบ ERP และให้คำปรึกษาด้าน recalculation logic",
      role: "Frontend Developer พัฒนา dashboard และให้คำปรึกษาเรื่อง recalculation logic",
      techStack: ["React", "JavaScript", "PostgreSQL", "n8n"],
      highlights: [
        "ผู้ใช้เห็นข้อมูล ERP แบบ real-time จากหน้าเดียว ส่วน chart component ที่ทำไว้ก็ถูกเอาไปใช้ซ้ำในโมดูลอื่น",
        "Dashboard แสดงข้อมูล ERP แบบ real-time",
        "ให้คำปรึกษาและออกแบบ recalculation logic",
        "Reusable chart/widget components",
      ],
    },
    {
      name: "CRM Core Modules (S-CRM)",
      category: "CRM Module",
      description: "โมดูลหลักของ S-CRM ที่ออกแบบและพัฒนาเอง ดูแลงานหลายส่วน ทั้ง lead capture ยาวไปจนถึงงาน after-sales service",
      role: "Lead Developer ออกแบบ data model, workflow engine และพัฒนาโมดูลทั้งหมด",
      techStack: ["React", "JavaScript", "Ant Design", "Chart.js", "Nivo", "ExcelJS", "Google Maps API", "Socket.IO", "PostgreSQL"],
      highlights: [
        "ย้ายงานที่เคยทำด้วยมือเข้าระบบ ทั้งการให้คะแนนและจ่าย lead การเปิดเคสจากอีเมล และการนับ SLA ทีมขายกับทีม service เลยทำงานบนข้อมูลชุดเดียวกันได้ยาวตั้งแต่รับ lead ไปจนปิดงานหลังการขาย",
        "Lead scoring ที่คำนวณคะแนนให้อัตโนมัติ พร้อม assignment rule ตาม segment, territory หรือ round-robin",
        "Opportunity pipeline แบบลาก stage ได้ ติดตาม probability, expected revenue และ commit target รายเดือนรายไตรมาส",
        "Sales forecast dashboard ด้วย Nivo",
        "Quotation builder ที่มี line item, ส่วนลด, ภาษี และ price list ตาม segment หรือ tier ของลูกค้า",
        "Sales Order ที่ convert มาจาก quotation ผ่าน approval และเดิน running number ตาม series",
        "Agreement management ที่ track ระยะสัญญาและแจ้งเตือนก่อนต่ออายุ",
        "Case workflow engine ที่ตั้ง process step ได้เอง มี auto-escalation และ SLA countdown ตาม priority ร่วมกับปฏิทินวันหยุด",
        "Field Service ที่จ่ายงานช่าง วางเส้นทางด้วย Google Maps และปิดงานด้วย checklist, รูปถ่าย และลายเซ็นดิจิทัล",
        "Email-to-Case เปิดเคสจากอีเมลขาเข้าให้อัตโนมัติพร้อมแจ้งเตือนทันที",
        "Import/Export Excel สำหรับงาน bulk และ reporting",
      ],
    },
    {
      name: "S-Loyalty Platform",
      category: "Loyalty & CRM Platform",
      description: "Loyalty platform ที่มีทั้งฝั่ง member (สะสมแต้ม แลกรางวัล) และ admin back-office เข้าไปขึ้นโครง translation system และ centralized CRUD framework ให้ทีมต่อยอดได้ทันที",
      role: "Lead Developer & Architect ขึ้นโครง translation system ออกแบบ centralized CRUD และ transaction management วาง architecture ทั้งฝั่ง admin และ LIFF app",
      techStack: ["Next.js 15", "React 19", "JavaScript", "Prisma", "PostgreSQL", "Redis (ioredis)", "Ant Design", "Tailwind CSS", "next-intl", "Lucia Auth", "Arctic (OAuth)", "MinIO", "MDX Editor", "dnd-kit", "Docker", "Yup", "GitHub Copilot"],
      highlights: [
        "วางรากฐานให้ทีมลงมือต่อได้ทันที ทั้ง CRUD framework และระบบหลายภาษา การเพิ่มภาษาใหม่เลยกลายเป็นงานของ admin ผ่าน CMS แทนที่จะเป็นงาน dev",
        "Translation system บน next-intl ที่เก็บ content แยกภาษาไว้ใน DB ให้ admin จัดการเองผ่าน CMS โดยไม่ต้องแก้ code",
        "Interactive transaction ที่ผูก Prisma $transaction กับ transaction ID ใน cookie จึง commit หรือ rollback ข้าม API call ได้",
        "CRUD helper ที่เติม audit field, สร้าง UUID และจัดการ nested relation ให้เอง",
        "Permission check ถึงระดับ table และ relation ที่ include เข้ามา แยก canRead/canWrite ราย role",
        "Member login ด้วย Lucia Auth ต่อกับ Arctic OAuth พร้อม OTP verification",
        "CMS หลายภาษาด้วย MDX editor บนโมเดล ContentPerLanguage",
        "Back-office ครบทั้ง user management, role-menu assignment, dashboard และ reporting",
        "MinIO file service กลางสำหรับรูป เอกสาร และ QR code",
        "แยก auth middleware เป็น 3 ชั้นตาม route pattern: admin ใช้ session, LIFF ใช้ LINE token, API ใช้ Basic Auth",
        "FormModel context ที่จัดการ state ของฟอร์มซ้อนแบบ parent-child",
        "เขียน in-app documentation ให้ dev ใหม่เข้าทีมได้เร็ว ครอบคลุมวิธีใช้ CRUD, naming convention และ deployment",
        "Dashboard สำหรับ point history และ member segmentation",
      ],
    },
    {
      name: "S-Hospitality Config-Driven Master",
      category: "Component System",
      description: "ออกแบบ component และ config system สำหรับหน้า master ให้ setup ได้ผ่าน config ล้วน ครอบคลุม record list, small list และ form",
      role: "Developer ออกแบบ config schema และพัฒนา component",
      techStack: ["Next.js", "React", "JavaScript"],
      highlights: [
        "หน้า master ใหม่เกิดจากการเขียน config แทนที่จะเขียน UI ใหม่ทุกครั้ง ทีมเลยเพิ่มหน้าเองได้โดยไม่ต้องแตะ component",
        "Setup หน้า master ได้โดยไม่ต้องเขียน UI code ใหม่",
        "ครอบคลุม 3 รูปแบบคือ record list, small list และ form",
      ],
    },
    {
      name: "Chat Assistance for S-CRM",
      category: "Feature / Integration",
      description: "ระบบ chat ในตัว CRM ที่ต่อ real-time messaging เข้ากับ workflow automation เพื่อทำ auto-assign, auto-reply และ escalation",
      role: "Developer ออกแบบและพัฒนา chat module ทั้งฝั่ง frontend และ integration layer",
      techStack: ["React", "Socket.IO", "n8n", "PostgreSQL", "Ant Design", "Emoji Picker"],
      highlights: [
        "ย้ายการคุยกับลูกค้าเข้ามาใน CRM ทีม support เลยตอบได้จากหน้าเดียวกับข้อมูลลูกค้า ส่วนคำถามซ้ำๆ ก็ให้ n8n auto-reply แทนการพิมพ์เอง",
        "Real-time chat ด้วย Socket.IO รองรับทั้งแบบ 1-on-1 และ group",
        "ต่อ n8n workflow automation สำหรับ auto-reply และ chatbot scenario",
        "ให้ AI Agent เข้าถึงข้อมูลลูกค้าเพื่อตอบได้ตรงจุด",
        "Emoji reaction และ rich text message",
        "จัดการห้องแชท ทั้งสร้างห้อง เชิญสมาชิก และ pin ข้อความ",
        "Quick Reply template สำหรับคำตอบที่ใช้บ่อย",
        "Track ข้อความที่ยังไม่อ่านพร้อมระบบแจ้งเตือน",
        "ช่วยลด response time ของทีม support",
      ],
    },
    {
      name: "Customer Portal",
      category: "Customer Service / Case Management",
      description: "Product ใหม่สำหรับจัดการ support case ตั้งแต่เปิดเคส ติดตามสถานะ reopen จนถึงปิดเคส ออกแบบเป็น modular product ที่ขายพ่วงกับ CRM customer service หรือใช้แบบ standalone ก็ได้",
      role: "Solo Architect & Full Stack Developer ออกแบบ architecture, schema และ UX flow เองทั้งหมด พัฒนาด้วย Claude Code",
      techStack: ["Next.js 15", "React 19", "TypeScript", "PostgreSQL", "Prisma", "Redis", "Tailwind CSS", "Ant Design", "Docker", "Nginx", "Claude Code"],
      highlights: [
        "เปิดเป็นสินค้าตัวใหม่ที่ขายแยกได้ ลูกค้าที่อยากได้แค่งาน support ไม่ต้องซื้อ CRM ทั้งชุด",
        "จัดการ case ได้ทั้ง lifecycle ทั้ง New case, Monitor, Reopen และ Close",
        "Dashboard ที่ดูสถานะเคสและ workload ได้จากหน้าเดียว",
      ],
    },
  ],

  education: [
    {
      institution: "อีสเทิร์นเอเชีย",
      degree: "วิศวกรรมศาสตรบัณฑิต",
      field: "วิศวกรรมคอมพิวเตอร์",
      startYear: 2012,
      endYear: 2017,
      gpa: 2.99,
    },
  ],

  courses: [
    { name: "n8n Workflow Automation" },
    { name: "Kiro AI-Powered IDE" },
    { name: "AI-Assisted Development Workflow" },
    { name: "Claude Code Agentic Development" },
  ],

  learningNow: ["Agentic Development with Claude Code", "System Design Patterns", "Platform Engineering"],

  hobbies: [
    { name: "เวทเทรนนิ่ง", icon: "🏋️", frequency: 5 },
    { name: "ดูบอล", icon: "⚽", frequency: 3 },
    { name: "เทนนิส", icon: "🎾", frequency: 3 },
    { name: "Boxing", icon: "🥊", frequency: 3 },
    { name: "Onsen", icon: "♨️", frequency: 3 },
    { name: "แบดมินตัน", icon: "🏸", frequency: 2 },
    { name: "เดินป่า", icon: "🥾", frequency: 2 },
    { name: "วิ่ง", icon: "🏃", frequency: 2 },
    { name: "เล่นเกม", icon: "🎮", frequency: 1 },
  ],

  cta: {
    message: "กำลังมองหา Lead Developer ที่ลงมือทำได้ตั้งแต่ architecture ถึง production? มาคุยกันครับ",
    availableMonthsFromNow: 2,
    resumePdfUrl: "/resume-pakorn.pdf",
    resumePdfUrlEn: "/resume-pakorn-en.pdf",
    qrCodeImage: "",
    availableForHire: true,
    preferredContact: "email",
  },

  settings: {
    language: "th" as const,
    designConcept: {
      name: "The Developer's Journey",
      philosophy: "เล่าเรื่องผ่าน visual narrative เป็นเรื่องของคนที่เริ่มจาก Programmer ธรรมดา เติบโตผ่านโปรเจกต์จริง จนกลายเป็น Lead ที่สร้างระบบให้องค์กรใหญ่ ทุก section คือ chapter ที่ค่อยๆ reveal ตัวตน",
      moodKeywords: [
        "narrative flow",
        "chapter-based",
        "progressive reveal",
        "cinematic depth",
        "personal yet professional",
      ],
      inspiration: "ผสมระหว่าง Stripe's annual letter ที่เล่าเรื่องผ่าน scroll, Apple product page ที่ reveal ทีละ layer และ timeline-based portfolio ที่ให้ความรู้สึกว่าคุณกำลังเดินทางไปกับเจ้าของ resume",
    },
  },
}
