/**
 * lib/me/data.ts — Raw resume data (unvalidated).
 * Do not import this directly — import `ME` from `lib/me` for the validated singleton.
 */

export const rawMeData = {
  profile: {
    firstName: "Pakorn",
    firstNameTH: "ปกร",
    lastName: "Chaowanaprasert",
    lastNameTH: "เชาวนประเสริฐ",
    nickname: "Kur",
    nicknameTH: "เกื้อ",
    title: "Lead Developer",
    tagline: "สร้างระบบที่ scale ได้จริง ด้วย code ที่คนอ่านรู้เรื่อง",
    location: "Bangna Bangkok, Thailand",
  },

  contact: {
    email: "patapuputapa@gmail.com",
    phone: "0885797989",
    // linkedin / website intentionally omitted until available
  },

  summary: {
    bio: "Lead Developer 8+ ปี ที่ไม่ได้แค่เขียน code — แต่ออกแบบ architecture, วาง database schema, deploy production และนำทีมส่งมอบ CRM platform ให้องค์กรกว่า 15 ราย ตั้งแต่ Millennium Auto ถึง CP-Meiji ถนัดสร้างระบบ config-driven ที่ทีมต่อยอดได้โดยไม่ต้องรอ dev — CRM ที่ทำครอบคลุมทั้ง Sales, Marketing, Service และ Field Service ครบวงจร",
    yearsOfExperience: 8,
    highlights: [
      "ส่งมอบ CRM platform ให้ 15+ องค์กร — ไม่มีงานไหนเหมือนกัน ครอบคลุม Sales, Marketing, Service, Field Service",
      "สร้าง config-driven system ที่ลดเวลา setup หน้าใหม่จากวันเหลือชั่วโมง",
      "ดูแล full cycle เอง — architecture → dev → deploy → migration",
      "นำทีม 5 คน พร้อม code review culture ที่ทำให้ quality คงที่",
      "Docker + Nginx + Jenkins + Kubernetes pipeline ที่ deploy ได้มั่นใจทุกวัน",
      "CRM ครบวงจร 90+ pages: Lead, Opportunity, Quotation, Case Management, Field Service, Campaign, Customer 360",
      "Real-time features: Socket.IO chat, AI chatbot, live notifications",
    ],
  },

  skills: {
    languages: [
      { name: "JavaScript", level: 90 },
      { name: "TypeScript", level: 80 },
      { name: "PHP", level: 60 },
    ],
    frameworks: [
      { name: "React", level: 90 },
      { name: "Next.js", level: 85 },
      { name: "Node.js", level: 80 },
      { name: "Ant Design", level: 90 },
      { name: "Material-UI", level: 75 },
      { name: "Vue.js", level: 65 },
      { name: "Prisma", level: 80 },
      { name: "Socket.IO", level: 75 },
    ],
    databases: [
      { name: "PostgreSQL", level: 85 },
      { name: "MySQL", level: 70 },
      { name: "Redis", level: 85 },
    ],
    devops: [
      { name: "Docker", level: 80 },
      { name: "Nginx", level: 75 },
      { name: "Jenkins", level: 70 },
      { name: "Kubernetes", level: 65 },
    ],
    tools: [
      { name: "Git", level: 90 },
      { name: "n8n", level: 75 },
      { name: "Figma", level: 60 },
    ],
    softSkills: [
      "Config-driven System Design — ลด dev time อย่างเป็นระบบ",
      "Team Leadership & Code Review Culture",
      "Database Schema Design & Migration Planning",
      "Technical Consulting — แปลง business need เป็น technical solution",
      "Cross-project Code Sharing & Reusable Architecture",
      "CRM Domain Expertise — Sales, Marketing, Service, Field Service workflows",
      "Multi-tenant SaaS Architecture Design",
      "Real-time System Design (WebSocket, Event-driven)",
    ],
  },

  experience: [
    {
      company: "MSC",
      workModel: "remote" as const,
      startDate: "2019-09",
      endDate: "present",
      roles: [
        { title: "Development Leader", startDate: "2025-01", endDate: "present" },
        { title: "Senior Programmer", startDate: "2021-01", endDate: "2024-12" },
        { title: "Programmer", startDate: "2019-09", endDate: "2020-12" },
      ],
      teamSize: 5,
      summary: "นำทีมพัฒนา CRM platform ให้ลูกค้าองค์กรขนาดใหญ่กว่า 15 ราย ครอบคลุมตั้งแต่ coding, deployment, database design จนถึง migration",
      responsibilities: [
        "ออกแบบ architecture และ database schema สำหรับ CRM platform ทั้ง S-CRM (React SPA) และ Next-S-CRM (Next.js 15)",
        "Deploy และดูแล production environment (Docker, Nginx, Jenkins, Kubernetes บน Azure & IBM Cloud)",
        "สร้าง shared components / code sharing ข้าม projects — reusable UI components กว่า 80+ ชิ้น",
        "วาง migration plan ย้ายระบบเก่าเข้า platform ใหม่ — design ทั้ง database schema, data mapping และ UX flow",
        "Lead ทีม dev 5 คน พร้อม code review culture ที่ทำให้ quality คงที่",
        "ออกแบบ CRM modules ครบวงจร: Lead, Opportunity, Quotation, Sales Order, Case Management, Field Service, Work Order, Campaign, Customer 360",
        "พัฒนา real-time features ด้วย Socket.IO — chat, notifications, live updates",
        "สร้าง workflow automation engine สำหรับ case management process steps",
        "ออกแบบ role-based access control + visible function system สำหรับ multi-tenant deployment",
        "Integrate Azure AD SSO (MSAL) สำหรับ enterprise clients",
      ],
      achievements: [
        { metric: "ส่งมอบ Custom CRM platform", value: "15+ ลูกค้าองค์กร", context: "Well, WDC, Panel Plus, Modernform, Central Food, Millennium Auto ฯลฯ" },
        { metric: "พัฒนา S-ERP", value: "All module dashboards", context: "ระบบ ERP ครบทุก module" },
        { metric: "สร้าง CP-Meiji Web App", value: "Solo architect — 30+ tables, 4 doc types, multi-dept approval", context: "ออกแบบเองทั้งหมดตั้งแต่ศูนย์ — DB schema, config-driven form engine, expression-based validation, row-level access control, Azure AD SSO, Redis caching — ไม่มี template ไม่มี reference" },
        { metric: "สร้าง Chat Assistance", value: "ระบบ chat ใน CRM", context: "Real-time Socket.IO chat + n8n chatbot + AI Agent context เพิ่ม engagement ของ end-user" },
        { metric: "พัฒนา Next-S-CRM", value: "CRM generation ใหม่", context: "ปรับ architecture ใหม่ทั้งหมดด้วย Next.js 15 — config-driven CRUD ลด dev time 70%" },
        { metric: "สร้าง S-Hospitality", value: "Dynamic & Master Components", context: "reusable components สำหรับสาย hospitality" },
        { metric: "CRM ครบวงจร", value: "90+ routes/pages", context: "Lead, Opportunity, Quotation, Sales Order, Case Management, Field Service, Work Order, Campaign, Customer 360, Dashboard, Reporting" },
        { metric: "Kubernetes deployment", value: "Azure + IBM Cloud", context: "Multi-environment CI/CD pipeline: dev, UAT, production" },
        { metric: "Landing Page Builder", value: "Marketing self-service tool", context: "ให้ทีม marketing สร้าง landing page ได้เองโดยไม่ต้องรอ dev" },
      ],
      clients: [
        "Well", "WDC", "Peneak", "Panel Plus", "Modernform", "Enraf",
        "CSH", "Central Food", "Traphet", "TBC", "T-Life", "T-Mill",
        "CP-Meiji", "Millennium Auto",
      ],
      techStack: ["JavaScript", "React", "Next.js", "Ant Design", "Material-UI", "Styled Components", "Socket.IO", "Chart.js", "Nivo", "n8n", "PostgreSQL", "Prisma", "Redis", "Docker", "Nginx", "Jenkins", "Kubernetes", "Azure AD (MSAL)", "Google Maps API", "Git"],
    },
    {
      company: "CDG",
      workModel: "onsite" as const,
      startDate: "2017-11",
      endDate: "2019-04",
      roles: [
        { title: "Programmer", startDate: "2017-11", endDate: "2019-04" },
      ],
      summary: "พัฒนา web application สำหรับระบบสอบและระบบเครื่องราชอิสริยาภรณ์ของหน่วยงานรัฐ",
      responsibilities: [
        "พัฒนา frontend ด้วย Vue.js และ React",
        "เขียน backend API ด้วย PHP",
        "ออกแบบและ optimize SQL queries",
      ],
      achievements: [
        { metric: "ปรับ performance", value: "ลด query time", context: "optimize SQL queries สำหรับข้อมูลขนาดใหญ่" },
        { metric: "เรียนรู้ stack ใหม่", value: "4 ภาษา/frameworks", context: "JS, Vue, React, PHP ภายในปีแรก" },
      ],
      clients: [],
      techStack: ["PHP", "JavaScript", "Vue.js", "React", "MySQL", "Git"],
    },
  ],

  projects: [
    {
      name: "S-CRM Platform",
      category: "CRM Platform",
      description: "CRM platform หลักของบริษัทที่ deploy ให้ลูกค้าองค์กรกว่า 14 ราย แต่ละรายมี customization และ module ที่แตกต่างกัน ดูแลและพัฒนาต่อเนื่องมากกว่า 4 ปี — ครอบคลุม Sales, Marketing, Service, Field Service และ Customer 360 ทั้งหมดในระบบเดียว",
      role: "Developer → Lead Developer — ร่วมพัฒนาตั้งแต่ต้นจนถึงนำทีม ดูแล architecture, deployment, code review และ migration",
      techStack: ["React 16", "JavaScript", "Ant Design", "Material-UI", "Styled Components", "Socket.IO", "Chart.js", "Nivo", "React Router", "Redux", "Axios", "PostgreSQL", "Redis", "Docker", "Nginx", "Jenkins", "Kubernetes", "Azure AD (MSAL)"],
      highlights: [
        "Deploy ให้ลูกค้าองค์กร 14 ราย แต่ละรายมี config และ module เป็นของตัวเอง",
        "ดูแล production environment ด้วย Docker + Nginx + Jenkins + Kubernetes (Azure & IBM Cloud)",
        "สร้าง shared component และ code sharing ข้าม client projects",
        "วาง migration plan ย้ายระบบเก่าเข้า platform ใหม่ — ไม่ใช่แค่วาง แต่ design และทำเองด้วยทั้ง database schema และ UX",
        "ระบบ CRM ครบวงจร: Lead Management, Opportunity Pipeline, Quotation, Sales Order, Case Management, Field Service, Work Order, Campaign, Customer 360, Dashboard & Reporting",
        "Real-time features: Socket.IO chat, live notifications, calendar sync",
        "AI/Chatbot integration: Chat Assistant, AI Agent context สำหรับ customer service",
        "Landing Page Builder สำหรับ marketing campaigns",
        "Customer Journey tracking และ Churn Rate analysis",
        "Scoring system สำหรับ lead qualification",
        "Workflow automation engine สำหรับ case management process",
        "SLA management และ escalation rules",
        "Google Maps integration สำหรับ field service routing",
        "Multi-format reporting: Excel export, PDF viewer, Chart dashboards (Nivo, Chart.js)",
        "Role-based access control + visible function system",
        "Azure AD SSO integration สำหรับ enterprise clients",
      ],
    },
    {
      name: "Full-S-CRM (Next-S-CRM)",
      category: "CRM Platform",
      description: "CRM platform generation ใหม่ที่ redesign architecture ทั้งหมดจาก S-CRM เดิม — ย้ายจาก React SPA มาเป็น Next.js 15 App Router, เปลี่ยนจาก raw SQL เป็น Prisma ORM, เพิ่ม Redis session/cache layer และ config-driven CRUD system ที่ลด boilerplate ได้กว่า 70%",
      role: "Lead Developer & Architect — ออกแบบ architecture ใหม่ทั้งหมด, สร้าง core framework, นำทีมพัฒนา",
      techStack: ["Next.js 15", "React 19", "JavaScript", "PostgreSQL", "Prisma", "Redis", "Docker", "Nginx", "Ant Design", "Tailwind CSS", "MinIO", "Azure AD", "n8n"],
      highlights: [
        "ออกแบบ Centralized CRUD Helper — auto audit fields, access control, transaction management และ audit logging ในที่เดียว",
        "สร้าง Config-driven Form & Table system — สร้างหน้า CRUD ใหม่ได้ภายในชั่วโมงจาก config ล้วน",
        "Redis-backed Transaction Management — interactive Prisma transactions ผ่าน Redis keys ไม่ต้อง hold DB connection",
        "ModelEvent System — post-write hooks ที่ trigger business logic อัตโนมัติหลัง CRUD operations",
        "Row-level Access Control — permission-based data filtering ที่ทำงานร่วมกับ CRUD helper โดยอัตโนมัติ",
        "Expression-based Validation Engine — dynamic validation rules ที่กำหนดผ่าน config (filtrex expressions) รองรับ CSP",
        "Multi-tenant ready — codebase เดียวรองรับลูกค้าหลายรายด้วย dynamic module system",
        "Azure AD SSO + Lucia v3 Auth — enterprise-grade authentication พร้อม PKCE flow",
        "Centralized Error Handling — log errors to DB + auto-create Azure Planner tasks สำหรับ critical issues",
        "ลด development time หน้าใหม่จาก 2-3 วัน เหลือ 2-3 ชั่วโมง ด้วย config-driven approach",
      ],
    },
    {
      name: "CP-Meiji Material Request",
      category: "Enterprise Web App",
      description: "ระบบ Material Request สำหรับ CP-Meiji ที่ออกแบบและ build เองทั้งหมดตั้งแต่ศูนย์ — ครอบคลุม multi-department approval workflow, dynamic form engine ที่ driven ด้วย config, expression-based validation, row-level access control, Azure AD SSO และ migration plan จากระบบเดิม รองรับ 4 document types (Create, Extend, Edit, Deletion)",
      role: "Solo Architect & Full Stack Developer — ออกแบบ architecture, DB schema, UX flow, expression engine, access control และ migration plan ด้วยตัวเอง ไม่มี template ไม่มี reference",
      techStack: ["Next.js 15", "React 19", "JavaScript", "PostgreSQL", "Prisma", "Redis", "Ant Design", "Tailwind CSS", "MinIO", "Azure AD (MSAL)", "Lucia Auth", "Docker", "Nginx"],
      highlights: [
        "ออกแบบ database schema 30+ tables — normalize ให้รองรับ dynamic fields, multi-level approval chain และ versioned material flow",
        "สร้าง config-driven form engine — MaterialFlow → Section → Input ที่ admin กำหนด field, validation, condition ได้โดยไม่ต้องแก้ code",
        "Expression engine (filtrex-based) สำหรับ dynamic validation rules: requireIf, disableIf, defaultIf ที่ evaluate ได้ทั้ง client/server แบบ CSP-safe",
        "Multi-level route approval system — รองรับ sequential + parallel department approvals, delegate managers, auto-activate next level",
        "Row-level access control — แยก permission ระดับ own/full/none ต่อ user ต่อ resource แบบ dynamic",
        "Azure AD SSO with PKCE flow + Lucia session management + Redis session store",
        "4 document types (Create/Extend/Edit/Deletion) แต่ละ type มี flow และ validation ต่างกัน จัดการบน codebase เดียว",
        "Auto-generate TXT export file ส่ง SAP เมื่อ approval chain ครบ พร้อม convert เป็น Master Item",
        "Redis caching layer — cache material flow config 5 นาที ลด DB query ซ้ำ",
        "Event-driven architecture (ModelEvent) — post-write hooks สำหรับ audit log, notification, cascading updates",
        "Centralized error handling — log ทุก error ลง DB + auto-create Azure Planner task สำหรับ critical issues",
        "วาง migration plan ย้ายข้อมูลจากระบบเดิมเข้า schema ใหม่โดยไม่สูญเสียข้อมูล",
      ],
    },
    {
      name: "S-ERP Dashboard",
      category: "ERP System",
      description: "พัฒนา dashboard สำหรับระบบ ERP และให้คำปรึกษาด้าน recalculation logic",
      role: "Frontend Developer — พัฒนา dashboard และ consult recal logic",
      techStack: ["React", "JavaScript", "PostgreSQL", "n8n"],
      highlights: [
        "Dashboard แสดงข้อมูล ERP แบบ real-time",
        "ให้คำปรึกษาและออกแบบ recalculation logic",
        "Reusable chart/widget components",
      ],
    },
    {
      name: "CRM Lead & Opportunity Management",
      category: "CRM Module",
      description: "ระบบจัดการ Lead และ Opportunity pipeline สำหรับ S-CRM — ครอบคลุมตั้งแต่ lead capture, qualification scoring, pipeline stages จนถึง conversion เป็น customer พร้อม commit target tracking และ sales forecast",
      role: "Lead Developer — ออกแบบ flow และพัฒนา module ทั้งหมด",
      techStack: ["React", "JavaScript", "Ant Design", "Chart.js", "PostgreSQL"],
      highlights: [
        "Lead scoring system — คำนวณคะแนนอัตโนมัติจาก criteria ที่กำหนด",
        "Opportunity pipeline — drag & drop stages, probability tracking, expected revenue",
        "Commit target — ตั้งเป้าหมายรายเดือน/ไตรมาส พร้อม dashboard tracking",
        "Lead assignment rules — auto-assign ตาม segment, territory, round-robin",
        "Sales forecast dashboard ด้วย Nivo charts",
        "Import/Export ข้อมูลจาก Excel สำหรับ bulk operations",
      ],
    },
    {
      name: "CRM Case Management & Field Service",
      category: "CRM Module",
      description: "ระบบ Case Management สำหรับ after-sales service — รองรับ case creation, SLA tracking, process step workflow, field service dispatch และ work order management พร้อม Google Maps integration สำหรับ routing",
      role: "Lead Developer — ออกแบบ workflow engine และพัฒนา module",
      techStack: ["React", "JavaScript", "Ant Design", "Google Maps API", "Socket.IO", "PostgreSQL"],
      highlights: [
        "Case workflow engine — configurable process steps, auto-escalation, SLA countdown",
        "SLA management — กำหนด response time / resolution time ตาม priority + holiday calendar",
        "Field Service module — dispatch technicians, route planning ด้วย Google Maps",
        "Work Order system — checklist-based task completion, photo evidence, digital signature",
        "Email-to-Case — auto-create case จาก incoming email",
        "Case category / sub-category hierarchy สำหรับ classification",
        "Report: Case tracking status, Job status tracking, Problem analysis",
        "Real-time notification เมื่อ case status เปลี่ยน",
      ],
    },
    {
      name: "CRM Quotation & Sales Order",
      category: "CRM Module",
      description: "ระบบ Quotation และ Sales Order สำหรับ S-CRM — รองรับ product catalog, price list management, discount rules, multi-currency และ approval workflow พร้อม PDF generation",
      role: "Lead Developer — ออกแบบ data model และพัฒนา module",
      techStack: ["React", "JavaScript", "Ant Design", "ExcelJS", "PostgreSQL"],
      highlights: [
        "Product catalog — product groups, sub-groups, UOM, price list management",
        "Quotation builder — line items, discount calculation, tax, total summary",
        "Price list groups — กำหนดราคาตาม customer segment / tier",
        "Sales Order workflow — convert จาก quotation, approval process",
        "Agreement/Contract management — track contract period, renewal alerts",
        "Excel export สำหรับ reporting และ bulk price update",
        "Series document — auto-generate running number ตาม format ที่กำหนด",
      ],
    },
    {
      name: "S-Loyalty Platform",
      category: "Loyalty & CRM Platform",
      description: "Loyalty platform ที่ครอบคลุมทั้ง member-facing app (สะสมแต้ม, แลกรางวัล) และ admin back-office — ขึ้นโครง translation system (next-intl + DB-driven content per language) และ centralized CRUD framework ที่ทีมต่อยอดได้ทันที รองรับ multi-language CMS, role-based access control, MinIO file storage และ interactive transaction management",
      role: "Lead Developer & Architect — ขึ้นโครง translation system, ออกแบบ centralized CRUD + transaction management, วาง architecture ทั้ง admin และ LIFF app",
      techStack: ["Next.js 15", "React 19", "JavaScript", "Prisma", "PostgreSQL", "Redis (ioredis)", "Ant Design", "Tailwind CSS", "next-intl", "Lucia Auth", "Arctic (OAuth)", "MinIO", "MDX Editor", "dnd-kit", "Docker", "Yup"],
      highlights: [
        "ขึ้นโครง Translation System — next-intl + DB-driven content per language ที่ admin จัดการภาษาได้เองผ่าน CMS โดยไม่ต้องแก้ code",
        "ออกแบบ Centralized CRUD Helper — auto audit fields (createdBy/updatedBy/createdPgm), UUID generation, nested relation handling, transaction management ในที่เดียว",
        "Interactive Transaction System — Prisma $transaction ผ่าน cookie-based transaction ID รองรับ multi-step operations ที่ commit/rollback ได้ข้าม API calls",
        "ModelEvent System — post-write hooks ที่ trigger business logic อัตโนมัติหลัง create/update/delete พร้อม preventData comparison",
        "Role-based Access Control — permission check ระดับ table + include relations, canRead/canWrite per role per table",
        "Member Authentication — Lucia Auth + Arctic OAuth สำหรับ member login, session management, OTP verification",
        "Multi-language CMS — MDX editor + ContentPerLanguage model ที่รองรับ rich text content หลายภาษา",
        "Admin Back-office — user management, role-menu assignment, dashboard, reporting modules",
        "MinIO File Storage — centralized file upload/download service รองรับ image, document, QR code",
        "Middleware Architecture — แยก auth middleware 3 layers: admin (session), LIFF (LINE token), API (Basic Auth) ตาม route pattern",
        "FormModel Context — nested form state management ที่รองรับ parent-child form hierarchy",
        "In-app Documentation — s-document section สำหรับ developer onboarding: CRUD usage, table naming conventions, deployment guide",
        "Dashboard & Reporting — overview metrics, point history analytics, member segmentation",
      ],
    },
    {
      name: "S-Hospitality Config-Driven Master",
      category: "Component System",
      description: "ออกแบบ component และ config system สำหรับหน้า master ให้ setup ได้ผ่าน config ล้วน ครอบคลุม record list, small list และ form",
      role: "Developer — ออกแบบ config schema และพัฒนา components",
      techStack: ["Next.js", "React", "JavaScript"],
      highlights: [
        "Config-driven — setup หน้า master ได้โดยไม่ต้องเขียน UI code ใหม่",
        "ครอบคลุม 3 รูปแบบ: record list, small list และ form",
        "ลดเวลาสร้างหน้า master ใหม่อย่างมีนัยสำคัญ",
      ],
    },
    {
      name: "Chat Assistance for S-CRM",
      category: "Feature / Integration",
      description: "ระบบ chat ในตัว CRM ที่รองรับทั้ง real-time messaging ระหว่าง user, chatbot automation ผ่าน n8n, AI Agent context สำหรับ customer service และ emoji reactions — เชื่อมต่อกับ workflow automation เพื่อ auto-assign, auto-reply และ escalation",
      role: "Developer — ออกแบบและพัฒนา chat module ทั้ง frontend และ integration layer",
      techStack: ["React", "Socket.IO", "n8n", "PostgreSQL", "Ant Design", "Emoji Picker"],
      highlights: [
        "Real-time chat ด้วย Socket.IO — รองรับ 1-on-1 และ group chat",
        "เชื่อมต่อ n8n workflow automation สำหรับ auto-reply และ chatbot scenarios",
        "AI Agent context — ให้ AI เข้าถึงข้อมูลลูกค้าเพื่อตอบคำถามได้ตรงจุด",
        "Emoji reactions และ rich text messaging",
        "Chat room management — สร้าง/จัดการห้อง, invite members, pin messages",
        "เพิ่ม engagement และลด response time ของ support team",
        "Quick Reply templates สำหรับ common responses",
        "Unread message tracking และ notification system",
      ],
    },
  ],

  education: [
    {
      institution: "อีสเทิร์นเอเชีย",
      degree: "วิศวกรรมศาสตรบัณฑิต",
      field: "วิศวกรรมคอมพิวเตอร์",
      startYear: 2012,
      endYear: 2017,
      gpa: 2.99,
    },
  ],

  courses: [
    { name: "n8n Workflow Automation", provider: "MSC (In-house)" },
    { name: "Kiro AI-Powered IDE", provider: "MSC (In-house)" },
    { name: "AI-Assisted Development Workflow", provider: "Self-study" },
  ],

  learningNow: ["AI-Assisted Development (Claude Code, Kiro)", "System Design Patterns", "Platform Engineering"],

  hobbies: [
    { name: "เวทเทรนนิ่ง", icon: "🏋️", frequency: 5 },
    { name: "ดูบอล", icon: "⚽", frequency: 3 },
    { name: "เทนนิส", icon: "🎾", frequency: 3 },
    { name: "Boxing", icon: "🥊", frequency: 3 },
    { name: "Onsen", icon: "♨️", frequency: 3 },
    { name: "แบดมินตัน", icon: "🏸", frequency: 2 },
    { name: "เดินป่า", icon: "🥾", frequency: 2 },
    { name: "วิ่ง", icon: "🏃", frequency: 2 },
    { name: "เล่นเกม", icon: "🎮", frequency: 1 },
  ],

  cta: {
    message: "กำลังมองหา Lead Developer ที่ลงมือทำได้ตั้งแต่ architecture ถึง production? มาคุยกันครับ",
    availableMonthsFromNow: 2,
    resumePdfUrl: "/resume-pakorn.pdf",
    qrCodeImage: "",
    availableForHire: true,
    preferredContact: "email",
  },

  settings: {
    language: "th" as const,
    designConcept: {
      name: "The Developer's Journey",
      philosophy: "เล่าเรื่องผ่าน visual narrative — resume ไม่ใช่แค่ list ข้อมูล แต่เป็นเรื่องเล่าของคนที่เริ่มจาก Programmer ธรรมดา เติบโตผ่านโปรเจกต์จริง จนกลายเป็น Lead ที่สร้างระบบให้องค์กรใหญ่ ทุก section คือ chapter ที่ค่อยๆ reveal ตัวตน",
      moodKeywords: [
        "narrative flow",
        "chapter-based",
        "progressive reveal",
        "cinematic depth",
        "personal yet professional",
      ],
      inspiration: "ผสมระหว่าง Stripe's annual letter ที่เล่าเรื่องผ่าน scroll, Apple product page ที่ reveal ทีละ layer, และ timeline-based portfolio ที่ให้ความรู้สึกว่าคุณกำลังเดินทางไปกับเจ้าของ resume — ไม่ใช่แค่อ่านข้อมูล แต่เข้าใจ journey",
    },
  },
}
